[package]
name = "net_ndn_router_cs"
version = "0.1.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>"]

[lib]
name = "net_ndn_router_cs"
crate-type = ["dylib"]

[dependencies]
rustfbp = "*"
capnp = "*"
